### ISSUE TITLE
crpush

### ISSUE THREAD

**Issue by zx900930** [Apen/epicseven#11]
Today I fight a guild full of rose defence.
I think we also need to add the positive push for the crpush calculation.
There are actually someone is running like rose/  roozid   speed team.

The problem is are we add a separate input? or use the current crbonus one?

**Comment by Apen** [comment]
As u want, we could use another field or keep this one. It just need to be easy to understand :-)

**Comment by zx900930** [comment]
ok, I think a separate one is better both for coding and users.

**Comment by Apen** [comment]
ok merged
