### ISSUE TITLE
Refactoring with full nodejs stack

### ISSUE THREAD

**Issue by Apen** [Apen/epicseven#16]
@zx900930 

Are you familiar with nodejs? Refactoring with nodejs and vuecli can help a lot to simplify the code.

**Comment by zx900930** [comment]
It doesn't bother me, I'm using VS code to write those things. And I already have a vuecli installed for some of my projects.

**Comment by Apen** [comment]
Its done, i have made some little modification, but it must be good.
Now i will refactoring into components to lightweight App.vue.

If you see some problem, post some issues :-)
