### ISSUE TITLE
Improve speed calculation

### ISSUE THREAD

**Issue by Apen** [Apen/epicseven#4]
@zx900930 

How can we improve the speed calculation? I propose 2 things:
* in the report, to take in account the 5% speed RNG, add an interval instead of a specific speed (-10 speed / +10 speed).
* you suggest a push back input field, its a good idea, but this calculation is not simple... the CR can be decrease (basared) or increase (Purrgis) so this field can be negative/positive. Then we need to add/sub this CR on the enemy.

Whats your point on this.

**Comment by zx900930** [comment]
The most common senareo is to calcul Basar's  speed,  Purrgis defence is normally not a high speed defence.
so we only need to consider this value is positive,  and remove 30% CR from basar

**Comment by zx900930** [comment]
The speed RNG is only 0% -5% RNG. so the interval  should be like  280(min)-294(max) speed.

**Comment by Apen** [comment]
> The speed RNG is only 0% -5% RNG. so the interval should be like 280(min)-294(min/0.95) speed.

Yes we are agree on that :-)

**Comment by Apen** [comment]
I try something in this branch "https://github.com/Apen/epicseven/tree/crpush", but not 100% sure if its good or not. Could you give me some feedbacks? For the moment, only for the forst hero.

**Comment by zx900930** [comment]
> I try something in this branch "https://github.com/Apen/epicseven/tree/crpush", but not 100% sure if its good or not. Could you give me some feedbacks? For the moment, only for the forst hero.

I'll test it out

**Comment by Apen** [comment]
Nice @zx900930 great job, im definitively agree with your calculation 💪

**Comment by Apen** [comment]
Must be good with #9

**Comment by zx900930** [comment]
@Apen gj, I believe we have done the part of speed calculations. maybe we can have a nice little favicon now.

**Comment by Apen** [comment]
We are all done here, favicon include.
