### ISSUE TITLE
[enhancement] add heros nickname to live search

### ISSUE THREAD

**Issue by zx900930** [Apen/epicseven#5]
The original hero's name in chinese are too long and hard to memories.
So we always using a nickname to call and search for a hero.

Like in english we using arby,  cdom , etc..

I want to add a new "nickname" property to characters.js

And make it as  data-tokens in the select-characters.js

`<option v-for="item in characters" :value="item.name" :data-tokens="item.nickname">`

and make it searchable as I did for the damage calculator
![image](https://user-images.githubusercontent.com/734749/87331278-00c66b00-c53a-11ea-8bdf-c0cc2a2c5d6d.png)

Don't know if this will break your script to update the characters list.

**Comment by Apen** [comment]
Are we going for global nickname or not? For exemple, in french, we use the same as EN. In this way, we could use a global mapping file where we list nicknames for a given character.

A separate file doesnt have side effects.

What do you think?

**Comment by zx900930** [comment]
> Are we going for global nickname or not? For exemple, in french, we use the same as EN. In this way, we could use a global mapping file where we list nicknames for a given character.
> 
> A separate file doesnt have side effects.
> 
> What do you think?

separate file is better, so we both dont need to change the script to update heros json.

**Comment by Apen** [comment]
Did you use an api for heroes/artifacts parsing @zx900930 ? I parse some html to generate the files, its not optimal.

**Comment by zx900930** [comment]
> Did you use an api for heroes/artifacts parsing @zx900930 ? I parse some html to generate the files, its not optimal.

Yes, I'm using epicseveDB's API  https://api.epicsevendb.com/
using a simple python script to parse the json.

[getheroFR.zip](https://github.com/Apen/epicseven/files/4922821/getheroFR.zip)

**Comment by Apen** [comment]
Ok, will use that too. I was checking this API few weeks ago and it was not uptodate, but its nice :-)

**Comment by zx900930** [comment]
@Apen We dont need all datas from the api.  We only need the id, name ,etc.  and the api includes  NPC with rarity = 1 and  1 star artifacts that perhaps no one would use.

So we'd better exclude them.

I upadated my python script

check out my script [here](https://github.com/Apen/epicseven/pull/10/files#diff-1328469e378726fc510bfa2b8d17ec39)

**Comment by Apen** [comment]
Yes i see, i kept image for future update, but we will see. Don't see for artifacts, youre right. Now we can use "_id" for nicknames.

**Comment by Apen** [comment]
See #3aa3ff2ffaa4af41dc5978038c6562931f717078

**Comment by Apen** [comment]
Just need to populate now :-)

**Comment by Apen** [comment]
I think we are good here
